#SPDX-License-Identifier: MIT-0
---

- name: Docker | Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Docker | Install Docker using official script
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  args:
    creates: /usr/bin/docker

- name: Docker | Enable and start Docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started