- hosts: all
  become: true
  tasks:
    - name: Para todos os containers Docker nos hosts
      ansible.builtin.shell: |
        docker ps -q | xargs -r docker stop
      ignore_errors: true

    - name: Remove todos os containers Docker nos hosts
      ansible.builtin.shell: |
        docker ps -aq | xargs -r docker rm
      ignore_errors: true
