---
- name: Ansible stat
  hosts: all
  tasks:
    - name: SISOP | Verificando se o arquivo existe
      ansible.builtin.stat: path=/home/pedro/data/example.json
      register: file

    - ansible.builtin.debug:
        msg: "File found"
      when: file.stat.exists

    - ansible.builtin.debug:
        msg: "File not found"
      when: file.stat.exists == false
